"""
Minimal Kernel for InfiniteOS demo:
- basic process table
- round-robin scheduler
- integration with PhiCore (encoding/decoding)
"""
import time
import threading
from collections import deque
from typing import Callable, Dict, Any

from src.kernel.phi_core import PhiCore

class Process:
    pid_counter = 1

        def __init__(self, target: Callable, name: str = "proc"):
                self.pid = Process.pid_counter
                        Process.pid_counter += 1
                                self.target = target
                                        self.name = f"{name}-{self.pid}"
                                                self.alive = True
                                                        self.context: Dict[str, Any] = {}

                                                            def run(self):
                                                                    try:
                                                                                self.target(self)
                                                                                        except Exception as e:
                                                                                                    print(f"[{self.name}] crashed: {e}")
                                                                                                            finally:
                                                                                                                        self.alive = False

                                                                                                                        class Kernel:
                                                                                                                            def __init__(self, layers: int = 4, tick: float = 0.05):
                                                                                                                                    self.process_table: Dict[int, Process] = {}
                                                                                                                                            self.ready = deque()
                                                                                                                                                    self.tick = tick
                                                                                                                                                            self.phi = PhiCore(layers=layers)
                                                                                                                                                                    self.lock = threading.Lock()
                                                                                                                                                                            self.running = False

                                                                                                                                                                                def spawn(self, target: Callable, name: str = "proc") -> int:
                                                                                                                                                                                        proc = Process(target, name)
                                                                                                                                                                                                self.process_table[proc.pid] = proc
                                                                                                                                                                                                        self.ready.append(proc.pid)
                                                                                                                                                                                                                # run in a separate thread to keep demo simple (not a real OS)
                                                                                                                                                                                                                        t = threading.Thread(target=self._run_proc_thread, args=(proc,))
                                                                                                                                                                                                                                t.daemon = True
                                                                                                                                                                                                                                        t.start()
                                                                                                                                                                                                                                                return proc.pid

                                                                                                                                                                                                                                                    def _run_proc_thread(self, proc: Process):
                                                                                                                                                                                                                                                            # Each process just runs its callable once in this demo.
                                                                                                                                                                                                                                                                    proc.run()
                                                                                                                                                                                                                                                                            # after run, mark done (already set in Process.run)
                                                                                                                                                                                                                                                                                    with self.lock:
                                                                                                                                                                                                                                                                                                if proc.pid in self.ready:
                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                    self.ready.remove(proc.pid)
                                                                                                                                                                                                                                                                                                                                                    except ValueError:
                                                                                                                                                                                                                                                                                                                                                                        pass

                                                                                                                                                                                                                                                                                                                                                                            def schedule_once(self):
                                                                                                                                                                                                                                                                                                                                                                                    with self.lock:
                                                                                                                                                                                                                                                                                                                                                                                                if not self.ready:
                                                                                                                                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                                                                                                                                            pid = self.ready[0]  # peek
                                                                                                                                                                                                                                                                                                                                                                                                                                        # simple round-robin rotate
                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.ready.rotate(-1)

                                                                                                                                                                                                                                                                                                                                                                                                                                                        def encode_state(self, bits):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                return self.phi.encode(bits)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def decode_state(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return self.phi.decode()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def harmonize(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return self.phi.harmonize()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def info(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "process_count": len(self.process_table),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "ready_queue": list(self.ready),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "phi_info": self.phi.info(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def run(self, runtime: float = 5.0):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.running = True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    start = time.time()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        while time.time() - start < runtime:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.schedule_once()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        time.sleep(self.tick)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                finally:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.running = False