# kernel/core.py
# ==========================================
# Núcleo principal do InfiniteOS
# ==========================================
import math
import random
from time import time
from kernel.scheduler import HarmonicScheduler
from kernel.semantic import SemanticLayer

class InfiniteKernel:
    def __init__(self):
            self.semantic = SemanticLayer()
                    self.layers = []

                        def evolve(self, data):
                                # processa o dado no nível harmônico
                                        harmonic = [d * 1.618 for d in data]
                                                meaning = self.semantic.interpret(harmonic)
                                                        self.layers.append(meaning)
                                                                return meaning

PHI = (1 + math.sqrt(5)) / 2


class InfiniteKernel:
    """
        Núcleo harmônico evolutivo do InfiniteOS.
            Responsável por coordenar camadas, processos e o ciclo de evolução do sistema.
                """

                    def __init__(self, mode="1 6 1 8"):
                            self.mode = mode
                                    self.state = {
                                                "boot_time": time(),
                                                            "layers": [],
                                                                        "phi": PHI,
                                                                                    "entropy": 0.0
                                                                                            }
                                                                                                    # Inicializa o scheduler harmônico
                                                                                                            self.scheduler = HarmonicScheduler(tick=0.05)
                                                                                                                    print(f"⚙️  Kernel initialized in φ-mode: {self.mode}")

                                                                                                                            # Registra processos internos
                                                                                                                                    self._register_internal_tasks()

                                                                                                                                        # ---------------------------------------------
                                                                                                                                            # Evolução e camadas
                                                                                                                                                # ---------------------------------------------
                                                                                                                                                    def evolve(self):
                                                                                                                                                            """
                                                                                                                                                                    Simula a evolução de uma camada do kernel,
                                                                                                                                                                            retornando metadados da nova camada harmônica.
                                                                                                                                                                                    """
                                                                                                                                                                                            t = len(self.state["layers"]) + 1
                                                                                                                                                                                                    entropy_delta = math.sin(t / PHI) * random.random()
                                                                                                                                                                                                            new_entropy = self.state["entropy"] + entropy_delta

                                                                                                                                                                                                                    layer = {
                                                                                                                                                                                                                                "index": t,
                                                                                                                                                                                                                                            "timestamp": time(),
                                                                                                                                                                                                                                                        "entropy_delta": entropy_delta,
                                                                                                                                                                                                                                                                    "description": f"Harmonic Layer {t} stabilized (ΔS={entropy_delta:.5f})"
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                    self.state["entropy"] = new_entropy
                                                                                                                                                                                                                                                                                            self.state["layers"].append(layer)
                                                                                                                                                                                                                                                                                                    return layer

                                                                                                                                                                                                                                                                                                        # ---------------------------------------------
                                                                                                                                                                                                                                                                                                            # Integração com scheduler harmônico
                                                                                                                                                                                                                                                                                                                # ---------------------------------------------
                                                                                                                                                                                                                                                                                                                    def _register_internal_tasks(self):
                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                    Registra processos internos automáticos do kernel:
                                                                                                                                                                                                                                                                                                                                            - harmonic_maintenance: mantém sincronização φ.
                                                                                                                                                                                                                                                                                                                                                    - entropy_logger: registra variações harmônicas.
                                                                                                                                                                                                                                                                                                                                                            """

                                                                                                                                                                                                                                                                                                                                                                    def harmonic_maintenance(ctx):
                                                                                                                                                                                                                                                                                                                                                                                while True:
                                                                                                                                                                                                                                                                                                                                                                                                # Ajusta pequenas variações entrópicas
                                                                                                                                                                                                                                                                                                                                                                                                                self.state["entropy"] *= 0.999 + random.random() * 0.0002
                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"[{ctx['name']}] φ-maintenance cycle")
                                                                                                                                                                                                                                                                                                                                                                                                                                                yield

                                                                                                                                                                                                                                                                                                                                                                                                                                                        def entropy_logger(ctx):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    while True:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    e = self.state["entropy"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"[{ctx['name']}] entropy={e:.6f}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    yield

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Registra tarefas no scheduler harmônico
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.scheduler.spawn(harmonic_maintenance, name="φ-maintenance", priority=3)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.scheduler.spawn(entropy_logger, name="entropy-logger", priority=1)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ---------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Execução principal do kernel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # ---------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def run(self, runtime=5.0):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Executa o ciclo harmônico do kernel por tempo determinado.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("🧠 Kernel harmonic cycle started...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.scheduler.run(runtime=runtime)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("🧩 Kernel harmonic cycle finished.")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Execução isolada para teste rápido
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                kernel = InfiniteKernel()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for _ in range(3):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            layer = kernel.evolve()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("Layer:", layer["description"])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        kernel.run(runtime=2.0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("Kernel state:", kernel.state)